pub mod consts {

    pub const BOSSES: [(&str, &str); 61] = [
        ("abyssal_sire", "B3"),
        ("alchemical_hydra", "C3"),
        ("artio", "D3"),
        ("barrows_chests", "E3"),
        ("bryophyta", "F3"),
        ("callisto", "G3"),
        ("calvarion", "H3"),
        ("cerberus", "I3"),
        ("chambers_of_xeric", "J3"),
        ("chambers_of_xeric_challenge_mode", "K3"),
        ("chaos_elemental", "L3"),
        ("chaos_fanatic", "B5"),
        ("commander_zilyana", "C5"),
        ("corporeal_beast", "D5"),
        ("crazy_archaeologist", "E5"),
        ("dagannoth_prime", "F5"),
        ("dagannoth_rex", "G5"),
        ("dagannoth_supreme", "H5"),
        ("deranged_archaeologist", "I5"),
        ("duke_sucellus", "J5"),
        ("general_graardor", "K5"),
        ("giant_mole", "L5"),
        ("grotesque_guardians", "B7"),
        ("hespori", "C7"),
        ("kalphite_queen", "D7"),
        ("king_black_dragon", "E7"),
        ("kraken", "F7"),
        ("kreearra", "G7"),
        ("kril_tsutsaroth", "H7"),
        ("mimic", "I7"),
        ("nex", "J7"),
        ("nightmare", "K7"),
        ("phosanis_nightmare", "L7"),
        ("obor", "B9"),
        ("phantom_muspah", "C9"),
        ("sarachnis", "D9"),
        ("scorpia", "E9"),
        ("skotizo", "F9"),
        ("spindel", "G9"),
        ("tempoross", "H9"),
        ("the_gauntlet", "I9"),
        ("the_corrupted_gauntlet", "J9"),
        ("the_leviathan", "K9"),
        ("the_whisperer", "L9"),
        ("theatre_of_blood", "B11"),
        ("theatre_of_blood_hard_mode", "C11"),
        ("thermonuclear_smoke_devil", "D11"),
        ("tombs_of_amascut", "E11"),
        ("tombs_of_amascut_expert", "F11"),
        ("tzkal_zuk", "G11"),
        ("tztok_jad", "H11"),
        ("vardorvis", "I11"),
        ("venenatis", "J11"),
        ("vetion", "K11"),
        ("vorkath", "L11"),
        ("wintertodt", "B13"),
        ("zalcano", "C13"),
        ("zulrah", "D13"),
        ("scurrius", "B15"),
        ("sol_heredit", "D15"), 
        ("lunar_chests", "C15"),
    ];

    pub const BASE_URL: &str = "https://api.wiseoldman.net/v2/groups/1500/gained?metric=";
    pub const BASE_URL_LEAGUES: &str = "https://api.wiseoldman.net/league/groups/40/gained?metric=";
}
